n = input('Qual é o seu nome? ')
i = input('Quantos anos você tem? ')
p = input('Quanto você pesa? ')
a = input('Qual é a sua altura? ')
print('Nome: ', n)
print('Idade: ', i, ' anos')
print('Peso: ', p, ' kilos')
print('Altura: ', a, ' metros')
